services:
  - type: web
    name: copa-phibra
    runtime: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port $PORT"
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "0"
      - key: SESSION_HTTPS_ONLY
        value: "1"
      - key: PYTHON_VERSION
        value: "3.11.9"
      - key: DATABASE_URL
        sync: false
